import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "./ContextAPIs/authcontext";
import { TaskProvider } from "./ContextAPIs/Taskcontext";
// import 'antd/dist/antd.css';

// import { NextUIProvider } from "@nextui-org/react/dist";
// import { Inter } from 'next/font/google'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TaskProvider>{children}</TaskProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
